
title: IIRA2001 - Programmering og data i økonomiske fag
author: Jonas Julius Harang and Hans Georg Schaathun
logo: ntnu.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
     - sphinx_iframes
