[project]
name = "iira2001-book2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter-book>=2.1.6",
    "jupyterlab>=4.6.2",
    "jupyterlab-rise>=0.43.1",
    "matplotlib>=3.11.1",
    "notebook>=7.6.1",
    "numpy>=2.5.1",
    "openai>=2.49.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pyjstat>=2.4.0",
    "requests>=2.34.2",
    "scikit-learn>=1.9.0",
    "scipy>=1.18.0",
    "seaborn>=0.13.2",
]
